import { CreditCard, FileText, Gauge, LockKeyhole, Rocket } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { ComingSoon, Empty, Header, Stat, Status } from "./shared";

export default function Billing({ routeParts }: { routeParts?: string[] }) {
  const organizations = trpc.workspace.organizations.useQuery(undefined, { retry: false });
  const organizationId = organizations.data?.[0]?.id;
  const status = trpc.billing.status.useQuery(undefined, { retry: false });
  const usage = trpc.billing.usage.useQuery(organizationId ? { organizationId } : undefined, { enabled: Boolean(organizationId), retry: false });
  const invoices = trpc.billing.invoices.useQuery(organizationId ? { organizationId } : undefined, { enabled: Boolean(organizationId), retry: false });
  const methods = trpc.billing.paymentMethods.useQuery({ organizationId: organizationId ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(organizationId), retry: false });
  const checkout = trpc.billing.checkout.useMutation({ onSuccess: result => result.configured ? window.location.assign(result.url) : toast.info(result.reason), onError: error => toast.error(error.message) });
  const latest = usage.data?.[0];
  const child = routeParts?.[1];
  const childLabel = child ? child.replaceAll("-", " ").replace(/\b\w/g, char => char.toUpperCase()) : undefined;
  return <><Header title={childLabel || "Billing"} crumb={childLabel ? `Billing / ${childLabel}` : "Billing"} action={<button className="vc-btn primary" disabled={!organizationId || checkout.isPending} onClick={() => organizationId && checkout.mutate({ organizationId, customerEmail: "billing@example.invalid", successUrl: window.location.href, cancelUrl: window.location.href })}><Rocket size={14} /> Upgrade plan</button>} /><div className="vc-grid-3"><Stat label="Current usage" value={latest ? `${latest.deploy_minutes} min` : "—"} /><Stat label="This period" value={latest ? `$${latest.estimated_amount}` : "$0"} /><Stat label="Plan" value={status.data?.plan.name ?? "Not configured"} /></div><div className="vc-card"><div className="vc-card-heading"><div><span className="vc-eyebrow">Plan limits</span><h3>{status.data?.plan.name ?? "Premium"}</h3></div><Status good={Boolean(status.data?.configured)}>{status.data?.configured ? "Configured" : "Not configured"}</Status></div><p>{status.data?.message ?? "Billing provider status unavailable."}</p><div className="vc-list-row"><Gauge size={16} /><span><strong>Deploy minutes</strong><small>{latest ? `${latest.deploy_minutes} minutes used` : "No usage telemetry"}</small></span><Status>Unknown limit</Status></div><div className="vc-list-row"><Gauge size={16} /><span><strong>Storage / bandwidth</strong><small>{latest ? `${latest.storage_gb} GB storage · ${latest.bandwidth_gb} GB bandwidth` : "No usage telemetry"}</small></span><Status>Unknown limit</Status></div></div><div className="vc-card"><span className="vc-eyebrow">Invoices</span><h3>Billing history</h3>{invoices.data?.length ? invoices.data.map(invoice => <div className="vc-list-row" key={invoice.id}><FileText size={16} /><span><strong>{invoice.invoice_ref || "Provider invoice"}</strong><small>{invoice.amount} {invoice.currency} · {invoice.issued_at || "Not issued"}</small></span><Status>{invoice.status}</Status></div>) : <Empty title="No invoices" body="Invoices appear only after a configured billing provider emits them." />}</div><div className="vc-card"><span className="vc-eyebrow">Payment methods</span><h3>Saved methods</h3>{methods.data?.length ? methods.data.map(method => <div className="vc-list-row" key={method.id}><CreditCard size={16} /><span><strong>{method.brand || method.provider}</strong><small>{method.last4 ? `•••• ${method.last4}` : "Provider reference not configured"}</small></span><Status good={method.status === "active"}>{method.status}</Status></div>) : <ComingSoon title="No payment method" body="Payment methods remain unavailable until the Stripe account and webhook contract are configured." />}</div><div className="vc-card"><LockKeyhole size={16} /><span><strong>Upgrade is gated safely</strong><small>The upgrade button never claims a purchase or payment when Stripe is not configured.</small></span></div></>;
}
