import type { EdgeEnforcementConfig } from "../securityPolicy";
import type { AdapterResult, SecurityEdgeConfig, SecurityEdgeAdapter } from "./platform";

export type SecurityEdgeArtifacts = {
  openresty: string;
  coraza: string;
  crowdsec: string;
  nftables: string;
  rateLimit: string;
  tunnel: string;
};

export type SecurityEdgeRequest = SecurityEdgeConfig;

function policy(input: SecurityEdgeRequest) {
  return input.desiredConfig as unknown as EdgeEnforcementConfig;
}

function renderOpenResty(config: EdgeEnforcementConfig) {
  const waf = config.waf.enabled ? "SecRuleEngine On\n    Include /etc/coraza/owasp-crs.conf" : "SecRuleEngine Off";
  const headers = config.tls.securityHeaders
    ? 'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;\n    add_header X-Content-Type-Options "nosniff" always;\n    add_header Referrer-Policy "strict-origin-when-cross-origin" always;'
    : "";
  return `# Generated by Cloud Wai. Do not edit manually.\nserver {\n    listen 443 ssl http2;\n    ssl_protocols ${config.tls.minimumVersion};\n    ${headers}\n    ${waf}\n    limit_req zone=cloudwai burst=${Math.max(10, Math.floor(config.rateLimit.requestsPerMinute / 10))} nodelay;\n    location / {\n        proxy_set_header X-Cloud-Wai-Edge true;\n        proxy_set_header X-Forwarded-Proto https;\n        proxy_pass http://tenant_origin_mtls;\n    }\n}`;
}

function renderCoraza(config: EdgeEnforcementConfig) {
  if (!config.waf.enabled) return "# Coraza disabled by policy\nSecRuleEngine Off";
  const sensitivity = config.waf.sensitivity === "strict" ? "BLOCK" : "LOG";
  return `# Generated by Cloud Wai. Coraza + OWASP CRS\nSecRuleEngine ${sensitivity}\nInclude /etc/coraza/crs-setup.conf\nInclude /etc/coraza/rules/*.conf\n# CRS anomaly threshold is controlled by policy level: ${config.level}`;
}

function renderCrowdSec(config: EdgeEnforcementConfig) {
  const enabled = config.botProtection.enabled ? "true" : "false";
  const aggressive = config.botProtection.challengeThreshold === "aggressive" ? "true" : "false";
  return `# Generated by Cloud Wai\napi:\n  enabled: ${enabled}\n  aggressive_bot_challenge: ${aggressive}\n  deny_private_networks: ${config.firewall.denyPrivateNetworks}\n  remediation: crowdsec-firewall-bouncer\n`;
}

function renderNftables(config: EdgeEnforcementConfig) {
  const privateDrop = config.firewall.denyPrivateNetworks ? "ip daddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } drop" : "";
  return `#!/usr/sbin/nft -f\n# Generated by Cloud Wai. Origin default-deny; edge mTLS is the only inbound path.\nflush table inet cloudwai\ntable inet cloudwai {\n  chain input { type filter hook input priority 0; policy drop;\n    iif lo accept\n    ct state established,related accept\n    tcp dport 22 ip saddr @admin_sources accept\n    tcp dport 443 accept\n    ${privateDrop}\n  }\n  chain forward { type filter hook forward priority 0; policy drop; }\n  chain output { type filter hook output priority 0; policy accept; }\n  set admin_sources { type ipv4_addr; flags interval; elements = { 127.0.0.1 } }\n}`;
}

function renderRateLimit(config: EdgeEnforcementConfig) {
  if (!config.rateLimit.enabled) return "# Rate limiting disabled by policy";
  return `# Generated by Cloud Wai\nlimit_req_zone $binary_remote_addr zone=cloudwai_per_ip:10m rate=${Math.max(1, Math.ceil(config.rateLimit.requestsPerMinute / 60))}r/s;\n# Policy ceiling: ${config.rateLimit.requestsPerMinute} requests/minute`;
}

function renderTunnel(config: EdgeEnforcementConfig) {
  return `# Generated by Cloud Wai hidden-origin model\n[edge]\nlisten = 51820\nmtls_required = true\norigin_public_inbound = false\nminimum_tls = ${config.tls.minimumVersion}\nfirewall_default_policy = drop\npolicy_level = ${config.level}`;
}

export function renderSecurityEdgeArtifacts(input: SecurityEdgeRequest): SecurityEdgeArtifacts {
  const config = policy(input);
  return {
    openresty: renderOpenResty(config),
    coraza: renderCoraza(config),
    crowdsec: renderCrowdSec(config),
    nftables: renderNftables(config),
    rateLimit: renderRateLimit(config),
    tunnel: renderTunnel(config),
  };
}

export class OpenSourceSecurityEdgeAdapter implements SecurityEdgeAdapter {
  readonly name = "openresty-coraza-crowdsec-nftables";

  async render(input: SecurityEdgeRequest): Promise<AdapterResult<SecurityEdgeArtifacts>> {
    return { status: "ready", data: renderSecurityEdgeArtifacts(input), message: "Security edge artifacts rendered; no host mutation performed." };
  }

  async preview(input: SecurityEdgeRequest) {
    const artifacts = renderSecurityEdgeArtifacts(input);
    return { status: "ready" as const, data: { diff: Object.keys(artifacts).map(path => ({ path, before: null, after: artifacts[path as keyof SecurityEdgeArtifacts] })), artifacts }, message: "Security edge artifacts rendered for preview." };
  }

  async apply(input: SecurityEdgeRequest) {
    const artifacts = renderSecurityEdgeArtifacts(input);
    if (!process.env.EDGE_HOST) {
      return { status: "not_configured" as const, data: null, message: "Security edge artifacts are rendered, but EDGE_HOST is not configured; no remote mutation was attempted." };
    }
    // Remote application is deliberately gated behind an explicitly provisioned
    // edge host. The concrete SSH/API transport is the only code that may mutate
    // the host and must be enabled after host identity and key verification.
    return { status: "not_configured" as const, data: null, message: `EDGE_HOST=${process.env.EDGE_HOST} is present, but remote transport is not enabled until the host trust/key contract is provisioned. ${Object.keys(artifacts).length} artifacts rendered.` };
  }
}

export function getSecurityEdgeAdapter() {
  return new OpenSourceSecurityEdgeAdapter();
}
