import { useEffect, useState, type ReactNode } from 'react';
import './demo.css';
import Auth from './Auth';
import Dashboard from './Dashboard';
import { supabase } from './lib/supabase';

const steps = [['01','Account','Google or email, password'],['02','Email','One-time verification code'],['03','Personal details','Legal name and mobile number'],['04','Identity','DOB, nationality, document and occupation'],['05','Residence','Address, city, region, postal code and tax residence'],['06','Security','Authenticator setup or skip'],['07','Complete','Account-ready confirmation']] as const;
type TestView='dashboard'|'admin'|'registration';
const randomToken=()=>{const b=new Uint8Array(24);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')};

export function AdminPanel({onHome,previewOnly=false}:{onHome?:()=>void;previewOnly?:boolean}){
 const goHome=onHome??(()=>undefined);
 const [section,setSection]=useState('Overview');
 const [query,setQuery]=useState('');
 const [toast,setToast]=useState('');
 const [testOpen,setTestOpen]=useState(false);
 const [view,setView]=useState<TestView>('dashboard');

 const users=[
  {id:'PW-10024',name:'Ayesha Rahman',email:'ayesha@example.test',type:'Personal',status:'Active',kyc:'Verified',balance:'$12,480.00'},
  {id:'PW-10023',name:'Atlas Studio Ltd',email:'finance@atlas.example.test',type:'Business',status:'Active',kyc:'Verified',balance:'$84,250.00'},
  {id:'PW-10022',name:'Nabil Hasan',email:'nabil@example.test',type:'Personal',status:'Review',kyc:'Pending',balance:'$2,180.00'},
  {id:'PW-10021',name:'Northstar Commerce',email:'ops@northstar.example.test',type:'Business',status:'Restricted',kyc:'Review',balance:'$41,900.00'},
 ];
 const txs=[
  {id:'TX-8F31A2',user:'Atlas Studio Ltd',direction:'IN',amount:'+ $4,250.00',rail:'Bank transfer',status:'Settled',risk:'Low'},
  {id:'TX-8F31A1',user:'Ayesha Rahman',direction:'OUT',amount:'- $980.00',rail:'International',status:'Pending',risk:'Medium'},
  {id:'TX-8F319C',user:'Northstar Commerce',direction:'OUT',amount:'- $18,600.00',rail:'Bank transfer',status:'Review',risk:'High'},
  {id:'TX-8F3194',user:'Nabil Hasan',direction:'IN',amount:'+ $1,200.00',rail:'Card',status:'Settled',risk:'Low'},
 ];
 const audit=[
  ['13:42','Admin session','Private admin access authenticated','121.200.220.137'],
  ['13:38','KYC queue','Document review opened for PW-10022','Admin'],
  ['13:31','Risk engine','High-value transaction flagged TX-8F319C','System'],
  ['13:08','Security','3 failed customer login attempts detected','System'],
 ];
 const filteredUsers=users.filter(u=>(u.name+' '+u.email+' '+u.id).toLowerCase().includes(query.toLowerCase()));
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),2600)};

 if(previewOnly)return <div className="admin-preview-wrap"><div className="admin-content"><div className="demo-eyebrow">TEST ADMIN · LIVE UI</div><h1>Control <em>center.</em></h1><p className="demo-lead">Investor-safe preview of the same administrative workspace. Production controls are disabled.</p><div className="admin-grid"><section className="admin-card primary-admin"><small>OPERATIONS</small><strong>ADMIN WORKSPACE</strong><p>Users, KYC, payments, risk, audit and system controls are organized in one operating console.</p></section><section className="admin-card"><small>SECURITY MODEL</small><strong>MAKER · CHECKER</strong><div className="admin-list"><span>Production data <b>Protected</b></span><span>Demo data <b>Synthetic</b></span><span>Financial writes <b>Disabled</b></span></div></section></div></div></div>;

 const nav=[
  ['Overview','Executive dashboard'],['Users','Customer administration'],['KYC & Compliance','Identity and compliance'],['Transactions','Payments and ledger'],['Risk & Fraud','Alerts and investigations'],['Approvals','Maker-checker queue'],['Audit & Security','Evidence and access'],['Reports','MIS and exports'],['Access Control','Roles and permissions'],['TEST INF','Investor preview'],['Settings','System controls'],
 ];
 const title=nav.find(x=>x[0]===section)?.[1]??'Operations';
 const action=(label:string)=>notify(label+' queued for approval');
 return <div className="bank-admin-shell">
  <aside className="bank-admin-sidebar">
   <button className="demo-brand" onClick={goHome}><span>P</span> PAYWAI</button>
   <div className="bank-admin-label">BANKING OPERATIONS</div>
   <div className="admin-operator"><span className="operator-avatar">W</span><span><b>Wasim</b><small>Super Administrator</small></span><i>●</i></div>
   <div className="bank-admin-nav">{nav.map(([name,sub])=><button key={name} className={section===name?'active':''} onClick={()=>{setSection(name);setTestOpen(false)}}><span>{name}</span><small>{sub}</small></button>)}</div>
   <button className="admin-exit" onClick={goHome}>← Back to website</button>
  </aside>
  <main className="bank-admin-main">
   <header className="bank-admin-topbar"><div><span>PAYWAI ADMINISTRATION</span><b>{title}</b></div><div className="admin-top-actions"><span className="secure-pill">● SECURE SESSION</span><button onClick={()=>notify('Session security panel opened')}>Security</button></div></header>
   <div className="bank-admin-content">
    {section==='Overview'&&<section>
      <div className="admin-page-head"><div><div className="demo-eyebrow">CONTROL CENTER</div><h1>Good afternoon, <em>Wasim.</em></h1><p>Operational health, financial movement and risk in one view.</p></div><button className="admin-primary" onClick={()=>action('New administrative change')}>+ Create request</button></div>
      <div className="admin-kpis"><div><small>TOTAL CUSTOMERS</small><strong>12,482</strong><span className="up">+8.4% this month</span></div><div><small>ACTIVE BALANCE</small><strong>$18.42M</strong><span>Across 6 currencies</span></div><div><small>TRANSACTIONS · 24H</small><strong>8,421</strong><span className="up">99.97% successful</span></div><div><small>OPEN RISK CASES</small><strong>17</strong><span className="danger">4 high priority</span></div></div>
      <div className="admin-two-col"><section className="admin-panel-card"><div className="card-heading"><div><small>TRANSACTION FLOW</small><h2>Today at a glance</h2></div><button onClick={()=>setSection('Transactions')}>View all</button></div><div className="flow-chart"><div className="flow-bars"><i style={{height:'42%'}}/><i style={{height:'63%'}}/><i style={{height:'48%'}}/><i style={{height:'78%'}}/><i style={{height:'56%'}}/><i style={{height:'91%'}}/><i style={{height:'70%'}}/><i style={{height:'84%'}}/></div></div><div className="chart-legend"><span>Incoming <b>$2.84M</b></span><span>Outgoing <b>$2.31M</b></span><span>Pending <b>$184K</b></span></div></section>
      <section className="admin-panel-card"><div className="card-heading"><div><small>ATTENTION REQUIRED</small><h2>Operational queue</h2></div></div><div className="queue-list"><button onClick={()=>setSection('KYC & Compliance')}><b>28</b><span>Identity reviews<small>Oldest 42 min</small></span><em>Review</em></button><button onClick={()=>setSection('Approvals')}><b>11</b><span>Approval requests<small>4 above normal</small></span><em>Approve</em></button><button onClick={()=>setSection('Risk & Fraud')}><b>4</b><span>High-risk alerts<small>Immediate attention</small></span><em className="red">Investigate</em></button><button onClick={()=>setSection('Transactions')}><b>7</b><span>Failed settlements<small>Needs reconciliation</small></span><em>Resolve</em></button></div></section></div>
      <section className="admin-panel-card"><div className="card-heading"><div><small>RECENT ACTIVITY</small><h2>Audit stream</h2></div><button onClick={()=>setSection('Audit & Security')}>Open audit log</button></div><div className="audit-table">{audit.map(([time,event,detail,actor])=><div key={time+event}><time>{time}</time><b>{event}</b><span>{detail}</span><small>{actor}</small></div>)}</div></section>
    </section>}

    {section==='Users'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">CUSTOMER ADMINISTRATION</div><h1>Users & <em>accounts.</em></h1><p>Search customers, review status and manage account lifecycle.</p></div><button className="admin-primary" onClick={()=>action('User creation')}>+ Add user</button></div><div className="admin-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or customer ID"/><button onClick={()=>notify('Filters opened')}>Filter</button><button onClick={()=>notify('Export queued')}>Export CSV</button></div><div className="admin-panel-card table-card"><div className="admin-table admin-users"><div className="th"><span>Customer</span><span>Type</span><span>Status</span><span>KYC</span><span>Balance</span><span>Action</span></div>{filteredUsers.map(u=><div className="tr" key={u.id}><span><b>{u.name}</b><small>{u.id} · {u.email}</small></span><span>{u.type}</span><span><i className={'status-dot '+u.status.toLowerCase()}/>{u.status}</span><span>{u.kyc}</span><span><b>{u.balance}</b></span><span><button onClick={()=>notify('Customer profile opened')}>View</button></span></div>)}</div></div></section>}

    {section==='KYC & Compliance'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">COMPLIANCE OPERATIONS</div><h1>KYC & <em>compliance.</em></h1><p>Review identity evidence, exceptions and customer verification status.</p></div><span className="module-status">● 28 pending reviews</span></div><div className="compliance-grid"><div><strong>28</strong><small>Pending KYC</small></div><div><strong>7</strong><small>Enhanced review</small></div><div><strong>4</strong><small>Rejected today</small></div><div><strong>96.8%</strong><small>Verification pass rate</small></div></div><div className="admin-panel-card"><div className="card-heading"><div><small>REVIEW QUEUE</small><h2>Cases requiring action</h2></div><button onClick={()=>notify('Compliance filters opened')}>Filter</button></div>{users.filter(u=>u.kyc!=='Verified').map(u=><div className="review-row" key={u.id}><span><b>{u.name}</b><small>{u.id} · {u.email}</small></span><span>{u.kyc} · {u.type}</span><span><button onClick={()=>action('KYC approval')}>Approve</button><button className="ghost" onClick={()=>action('KYC rejection')}>Reject</button></span></div>)}</div></section>}

    {section==='Transactions'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">PAYMENT OPERATIONS</div><h1>Transactions & <em>ledger.</em></h1><p>Monitor payment lifecycle, settlement and exceptions.</p></div><button className="admin-primary" onClick={()=>action('Transaction adjustment')}>+ New adjustment</button></div><div className="admin-kpis compact"><div><small>VOLUME TODAY</small><strong>$5.15M</strong><span>8,421 transactions</span></div><div><small>SETTLED</small><strong>99.97%</strong><span>Within SLA</span></div><div><small>PENDING</small><strong>184</strong><span>$184K total</span></div><div><small>FAILED</small><strong>7</strong><span className="danger">Needs action</span></div></div><div className="admin-panel-card table-card"><div className="admin-table transaction-table"><div className="th"><span>Reference</span><span>Customer</span><span>Direction</span><span>Amount</span><span>Rail</span><span>Status</span><span>Risk</span></div>{txs.map(t=><div className="tr" key={t.id}><span><b>{t.id}</b><small>18 Sep 2026 · 13:42</small></span><span>{t.user}</span><span className={t.direction==='IN'?'in':'out'}>{t.direction}</span><span><b>{t.amount}</b></span><span>{t.rail}</span><span><i className={'status-dot '+t.status.toLowerCase()}/>{t.status}</span><span><i className={'risk '+t.risk.toLowerCase()}>{t.risk}</i></span></div>)}</div></div></section>}

    {section==='Risk & Fraud'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">FINANCIAL CRIME CONTROLS</div><h1>Risk & <em>fraud.</em></h1><p>Prioritize alerts, investigate suspicious activity and manage rules.</p></div><button className="admin-primary" onClick={()=>action('Risk rule change')}>+ New rule</button></div><div className="risk-grid"><div className="risk-banner high"><strong>4</strong><span>High priority alerts<small>2 require action within 30 min</small></span></div><div className="risk-banner"><strong>13</strong><span>Medium alerts<small>Auto-triage enabled</small></span></div><div className="risk-banner"><strong>99.4%</strong><span>Rule uptime<small>Last evaluated 13:42</small></span></div></div><div className="admin-panel-card"><div className="card-heading"><div><small>ACTIVE ALERTS</small><h2>Investigation queue</h2></div></div>{[['High','TX-8F319C','Velocity + amount anomaly','Northstar Commerce'],['High','TX-8F30D1','New device + unusual geography','Ayesha Rahman'],['Medium','TX-8F2FC1','Multiple failed authentication attempts','Nabil Hasan']].map(a=><div className="review-row" key={a[1]}><span><i className={'risk '+a[0].toLowerCase()}>{a[0]}</i><b>{a[1]}</b></span><span>{a[2]}<small>{a[3]}</small></span><button onClick={()=>action('Risk case investigation')}>Investigate</button></div>)}</div></section>}

    {section==='Approvals'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">DUAL CONTROL</div><h1>Approval <em>queue.</em></h1><p>Maker-checker workflow prevents one operator from approving their own change.</p></div><span className="module-status">● 11 awaiting authorization</span></div><div className="approval-card"><div><small>HIGH-VALUE PAYMENT</small><strong>$18,600.00</strong><span>TX-8F319C · Northstar Commerce</span></div><div className="approval-meta"><span>Maker <b>Operations 04</b></span><span>Required <b>Senior Authorizer</b></span><span>Risk <i className="risk high">High</i></span></div><button className="admin-primary" onClick={()=>action('Approval decision')}>Review & authorize</button></div><div className="approval-card"><div><small>USER ACCESS CHANGE</small><strong>Role elevation</strong><span>Request AC-2041 · Operations</span></div><div className="approval-meta"><span>Maker <b>Admin Maker</b></span><span>Required <b>Admin Checker</b></span><span>Risk <i className="risk medium">Medium</i></span></div><button className="admin-primary" onClick={()=>action('Access approval')}>Review & authorize</button></div></section>}

    {section==='Audit & Security'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">EVIDENCE & ACCESS</div><h1>Audit & <em>security.</em></h1><p>Every sensitive action should be attributable, reviewable and exportable.</p></div><button className="admin-primary" onClick={()=>notify('Evidence export queued')}>Export evidence</button></div><div className="security-grid"><div><strong>100%</strong><small>Admin actions logged</small></div><div><strong>24h</strong><small>Session visibility</small></div><div><strong>3</strong><small>Failed admin logins</small></div><div><strong>MFA</strong><small>Required for privileged roles</small></div></div><div className="admin-panel-card"><div className="card-heading"><div><small>IMMUTABLE EVENT STREAM</small><h2>Security audit trail</h2></div><button onClick={()=>notify('Audit filters opened')}>Filter</button></div><div className="audit-table">{[...audit,['12:58','Access control','Role permission reviewed','Admin Checker'],['12:41','Configuration','Transaction limit policy changed','Admin Maker']].map(([time,event,detail,actor])=><div key={time+detail}><time>{time}</time><b>{event}</b><span>{detail}</span><small>{actor}</small></div>)}</div></div></section>}

    {section==='Reports'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">MANAGEMENT INFORMATION</div><h1>Reports & <em>exports.</em></h1><p>Operational, financial and compliance reporting for management review.</p></div></div><div className="report-grid">{[['Daily transaction report','Volume, success rate, rails','CSV · PDF'],['Customer/KYC report','Onboarding and verification status','CSV · XLSX'],['Risk & AML report','Alerts, cases and decisions','CSV · PDF'],['Audit evidence pack','Privileged actions and approvals','PDF · JSON'],['Settlement reconciliation','Matched and unmatched items','CSV · XLSX'],['User access review','Roles, permissions and changes','CSV · PDF']].map(([a,b,c])=><button key={a} onClick={()=>notify(a+' generation queued')}><small>{c}</small><strong>{a}</strong><span>{b}</span><em>Generate →</em></button>)}</div></section>}

    {section==='Access Control'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">PRIVILEGED ACCESS</div><h1>Roles & <em>permissions.</em></h1><p>Least privilege, segregation of duties and dual authorization for sensitive changes.</p></div><button className="admin-primary" onClick={()=>action('Role change')}>+ Create role</button></div><div className="roles-table">{[['Super Administrator','Full control','1','MFA + dual control'],['Admin Checker','Approve admin changes','2','MFA required'],['Operations Manager','Payments + exceptions','4','Maker only'],['Compliance Officer','KYC + AML cases','3','Restricted PII'],['Support Officer','Customer support','8','No financial writes']].map(r=><div key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]} users</span><span>{r[3]}</span><button onClick={()=>notify('Role details opened')}>Manage</button></div>)}</div><div className="admin-note"><b>Segregation of duties</b><span>Admin Maker cannot approve their own access or configuration change. Financial actions require an independent checker according to value band.</span></div></section>}

    {section==='TEST INF'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">INVESTOR PRESENTATION</div><h1>TEST <em>INF.</em></h1><p>Safe investor preview of dashboard, registration and admin workflows.</p></div><button className="admin-primary" onClick={()=>notify('Investor preview link control opened')}>Manage preview</button></div><div className="admin-grid"><section className="admin-card primary-admin"><small>LIVE COMPONENTS</small><strong>3 PREVIEWS</strong><p>Dashboard, Registration and Admin are rendered from the real application components with synthetic data.</p><button className="admin-open-test" onClick={()=>{setTestOpen(true);setView('dashboard')}}>Open TEST INF</button></section><section className="admin-card"><small>ISOLATION</small><strong>SAFE DEMO MODE</strong><div className="admin-list"><span>Production writes <b>Disabled</b></span><span>Customer data <b>Hidden</b></span><span>Demo data <b>Synthetic</b></span></div></section></div>{testOpen&&<div className="test-inf-workspace"><div className="test-inf-header"><div><div className="demo-eyebrow">TEST INF</div><h2>Investor <em>preview.</em></h2></div><span>PRIVATE · ADMIN SESSION</span></div><div className="test-inf-tabs"><button className={view==='dashboard'?'selected':''} onClick={()=>setView('dashboard')}>Test Dashboard</button><button className={view==='admin'?'selected':''} onClick={()=>setView('admin')}>Test Admin</button><button className={view==='registration'?'selected':''} onClick={()=>setView('registration')}>Test Registration</button></div>{view==='dashboard'&&<LivePreview title="LIVE DASHBOARD PREVIEW" note="Synthetic data only"><Dashboard demoMode onBack={()=>undefined}/></LivePreview>}{view==='admin'&&<TestAdmin/>}{view==='registration'&&<LivePreview title="LIVE REGISTRATION PREVIEW" note="No database writes"><Auth demoMode initialMode="signup" onBack={()=>undefined} onSuccess={()=>undefined}/></LivePreview>}</div>}</section>}

    {section==='Settings'&&<section><div className="admin-page-head"><div><div className="demo-eyebrow">SYSTEM GOVERNANCE</div><h1>System <em>settings.</em></h1><p>Controls that affect authentication, transaction policies, integrations and the investor environment.</p></div></div><div className="settings-grid">{[['Authentication','MFA required for privileged users','Enabled'],['Transaction controls','High-value payments require checker','Enabled'],['Risk monitoring','Real-time anomaly rules','Enabled'],['Audit retention','Privileged actions retained','Configured'],['Investor environment','TEST INF isolated from production','Protected'],['Notifications','Critical risk alerts','Enabled']].map(s=><div key={s[0]}><span><b>{s[0]}</b><small>{s[1]}</small></span><strong>{s[2]}</strong><button onClick={()=>action(s[0]+' change')}>Configure</button></div>)}</div><div className="admin-note warning"><b>Production safety</b><span>Never allow the browser to write balances, settle payments or modify privileged configuration directly. Those operations belong behind server-side authorization, maker-checker controls and immutable audit logging.</span></div></section>}
   </div>
   {toast&&<div className="admin-toast">{toast}</div>}
  </main>
 </div>;
}
function AdminSettings({visibility,investorLink,message,onGenerate,onRevoke}:{visibility:'public'|'private';investorLink:string;message:string;onGenerate:()=>void;onRevoke:()=>void}){
 return <div className="admin-content"><div className="demo-eyebrow">ADMIN SETTINGS</div><h1>Control <em>access.</em></h1><p className="demo-lead">Public TEST INF never exposes the Admin route. Access is granted only through a temporary tokenized investor link.</p><section className="admin-card visibility-card"><div><small>TEST INF ACCESS</small><h2>{visibility==='public'?'Investor link active':'Private mode'}</h2><p>{visibility==='public'?'Only the generated /i/&lt;token&gt; link can open the investor preview.':'No investor token is currently active.'}</p></div><div className="visibility-control"><strong>{visibility==='public'?'PUBLIC':'PRIVATE'}</strong><button onClick={onGenerate}>Generate new link</button><button onClick={onRevoke} disabled={visibility!=='public'}>Revoke link</button></div></section>{investorLink&&<section className="admin-card investor-link-card"><small>ACTIVE INVESTOR LINK</small><code>{investorLink}</code><button onClick={()=>navigator.clipboard?.writeText(investorLink)}>Copy link</button></section>}{message&&<div className="test-note">{message}</div>}</div>
}
function TestInfWorkspace({visibility,view,onView}:{visibility:'public'|'private';view:TestView;onView:(v:TestView)=>void}){
 if(visibility!=='public')return <div className="forbidden"><div><strong>403</strong><h1>Test INF is private</h1><p>Generate a temporary investor link in Admin Settings when you need to present it.</p></div></div>;
 return <div className="test-inf-workspace"><div className="test-inf-header"><div><div className="demo-eyebrow">TEST INF</div><h1>Investor <em>preview.</em></h1></div><span>PUBLIC · TOKEN PROTECTED</span></div><div className="test-inf-tabs"><button className={view==='dashboard'?'selected':''} onClick={()=>onView('dashboard')}>Test Dashboard</button><button className={view==='admin'?'selected':''} onClick={()=>onView('admin')}>Test Admin</button><button className={view==='registration'?'selected':''} onClick={()=>onView('registration')}>Test Registration</button></div>{view==='dashboard'&&<LivePreview title="LIVE DASHBOARD PREVIEW" note="Same Dashboard component · synthetic data only"><Dashboard demoMode onBack={()=>undefined}/></LivePreview>}{view==='admin'&&<TestAdmin/>}{view==='registration'&&<LivePreview title="LIVE REGISTRATION PREVIEW" note="Same Auth component · backend writes disabled"><Auth demoMode initialMode="signup" onBack={()=>undefined} onSuccess={()=>undefined}/></LivePreview>}</div>
}
function LivePreview({title,note,children}:{title:string;note:string;children:ReactNode}){return <section className="live-preview-card"><div className="live-preview-banner"><strong>{title}</strong><span>{note}</span></div>{children}</section>}
function TestAdmin(){return <LivePreview title="LIVE ADMIN PREVIEW" note="Same Admin Panel component · investor-safe preview"><AdminPanel previewOnly/></LivePreview>}
export function InvestorPreview({token}:{token:string}){
 const [allowed,setAllowed]=useState<boolean|null>(null);
 useEffect(()=>{let live=true;void supabase.rpc('check_demo_token',{p_token:token}).then(({data})=>{if(live)setAllowed(data===true)}).catch(()=>{if(live)setAllowed(false)});return()=>{live=false}},[token]);
 if(allowed===null)return <div className="demo-loading">Checking investor access…</div>;
 if(!allowed)return <div className="forbidden public-forbidden"><div><strong>403</strong><h1>Investor link is invalid</h1><p>This temporary TEST INF link is expired, revoked or incorrect.</p></div></div>;
 return <InvestorPreviewContent/>;
}
function InvestorPreviewContent(){const [view,setView]=useState<TestView>('dashboard');return <div className="investor-public-shell"><header className="investor-public-header"><button className="demo-brand" onClick={()=>window.location.href='/'}><span>P</span> PAYWAI</button><span>INVESTOR PREVIEW · TOKEN VERIFIED</span></header><main className="test-inf-public"><div className="test-inf-header"><div><div className="demo-eyebrow">TEST INF</div><h1>Investor <em>preview.</em></h1></div><span>PUBLIC · TOKEN VERIFIED</span></div><div className="test-inf-tabs"><button className={view==='dashboard'?'selected':''} onClick={()=>setView('dashboard')}>Test Dashboard</button><button className={view==='admin'?'selected':''} onClick={()=>setView('admin')}>Test Admin</button><button className={view==='registration'?'selected':''} onClick={()=>setView('registration')}>Test Registration</button></div>{view==='dashboard'&&<LivePreview title="LIVE DASHBOARD PREVIEW" note="Real Dashboard component · synthetic data"><Dashboard demoMode onBack={()=>window.location.href='/'}/></LivePreview>}{view==='admin'&&<TestAdmin/>}{view==='registration'&&<LivePreview title="LIVE REGISTRATION PREVIEW" note="Real Auth component · no database writes"><Auth demoMode initialMode="signup" onBack={()=>window.location.href='/'} onSuccess={()=>undefined}/></LivePreview>}</main></div>}
